### ISSUE TITLE
Feature Request: Shorthand signature for emit

### ISSUE THREAD

**Issue by brianneisler** [serverless/fdk#35]
The current spec outlines the emit function signature as the following

```js
gateway.emit({
  event: "userCreated",
  data: JSON.stringify({ name: "Austen" }),
})
```

This verbose signature is good as there are additional properties we may want to add like the `meta` property etc as the gateway matures. https://github.com/serverless/event-gateway/issues/179

However, it may be nice to offer a shorthand signature in some cases where all you're doing is sending events with some simple data payload.

```js
gateway.emit('some.event.type', {
  'i': 'am data'
})
```

**Comment by nikgraf** [comment]
I suggest we keep aim for an API where there is one way of doing the same thing. Multiple ways just make it harder to document and lead to more confusion for newcomers and makes it harder for users to parse others people code of they use the other style.

Should we change `emit` to the proposed signature?

Personally I believe the initial version is better because:
- having one argument is more extensible for the future
- having one argument makes it easier for functional programming in JS since currying is not needed
- being explicit about the key `event` helps to parse the code

**Comment by RafalWilinski** [comment]
For me, signature proposed by @brianneisler seems more natural for two reasons:
- There's a clear separation of `event` name/type which basically routes the event and the "payload"
- It's very similar to sending a POST request in `axios`, `fetch`, or many other libraries performing similar things. I think this might make things more intuitive for new developers. 

Regarding one argument being more extensible: second parameter of the function could be an object containing `data`, `meta` and all other things (just like axios/fetch).
